### ISSUE TITLE
How to find constructors references?

### ISSUE THREAD

**Issue by MelodiousThonk** [dsherret/ts-simple-ast#1155]
Hello,

I would like to have access to the references of a class constructor, but I can't via the findReferences method. Is there a way to do it? I noticed that objects of type constructorDeclaration don't have a findReferences method while methodDeclaration has it. I also noticed that VSCode finds references for both (probably via tsserver).

Yours faithfully,
Hamza

**Comment by dsherret** [comment]
Was just an oversight because constructors don't have a name property. I opened #1156.

For now, try using `project.getLanguageService().findReferences(ctorDecl);` (or `findReferencesAsNodes`) and provide it the constructor declaration. It might work (didn't try it out because I don't have time at the moment)

**Comment by MelodiousThonk** [comment]
Thank you!

**Comment by MelodiousThonk** [comment]
It works!
