### ISSUE TITLE
project.getDirectory("path/to/dir") returns always undefined

### ISSUE THREAD

**Issue by enzomanuelmangano** [dsherret/ts-simple-ast#1175]
**Describe the bug**

Version: 11.0.2

**To Reproduce**

I can't understand why the result of "project.getDirectory(currentDir)" is undefined.
```ts
import { Project } from 'ts-morph';

const testDir = async () => {
  const project = new Project();

  const currentDir = project.getFileSystem().getCurrentDirectory();
  console.log({ currentDir });
  console.log(project.getDirectory(currentDir));

  await project.save();
};

(async () => {
  await testDir();
})();

```

If instead I create a file and access the current directory through the file, I get the desired result.
```ts
import { Project } from 'ts-morph';

const testDir = async () => {
  const project = new Project();

  const sourceFile = project.createSourceFile('test.ts');
  console.log(sourceFile.getDirectory());

  await project.save();
};

(async () => {
  await testDir();
})();

```

**Expected behavior**

I expect the same result (in terms of logs) from the two approaches. In case my assumptions are wrong, is it possible through the package to access the current directory without creating a file?
```ts
// First
const currentDir = project.getFileSystem().getCurrentDirectory();
console.log(project.getDirectory(currentDir));

// Second 
const sourceFile = project.createSourceFile('test.ts');
console.log(sourceFile.getDirectory());
```

Thank you in advance for the support and maintenance of this amazing package.

**Comment by dsherret** [comment]
The reason is because the `Project` initially has no directories or source files if it is not initialized with any source files or provided a tsconfig.json:

```ts
const project = new Project();

console.log(project.getDirectories().length); // 0
console.log(project.getSourceFiles().length); // 0
```

The `project.getFileSystem().getCurrentDirectory()` method returns the file system's current working directory. So if you create a source file in the current working directory by doing something like `project.createSourceFile('test.ts')`, then `project.getDirectory(currentDir)` will now return a result.

You can initialize the project by adding existing directories, files, or creating new files in that project. See https://ts-morph.com/setup/adding-source-files

Hopefully that makes sense. Let me know if you have any other questions.

**Comment by enzomanuelmangano** [comment]
Sorry for wasting your time. Thank you for the support, everything is very clear.
