### ISSUE TITLE
Braces of classes with `extends` or `implements`-clauses aren't placed on new lines with `placeOpenBraceOnNewLineForControlBlocks` and `placeOpenBraceOnNewLineForFunction` enabled

### ISSUE THREAD

**Issue by neurolag** [dsherret/ts-simple-ast#1179]
**Describe the bug**
Even though, `placeOpenBraceOnNewLineForControlBlocks` and `placeOpenBraceOnNewLineForFunctions` are set to `true`, the opening brace of `class`es with `extends` or `implements`-clauses aren't placed on a new line.

Version: 11.0.3

The opening brace of `class`es are placed on the same line with `placeOpenBraceOnNewLineForControlBlocks` set to `true`.

**To Reproduce**

Create a class and format it with `placeOpenBraceOnNewLineForControlBlocks` enabled.
Notice that the error only occurs if the class has `implements`- or `extends`-clauses

```ts
import { Project } from "ts-morph";

let sourceFile = new Project().createSourceFile("test.ts", null, { overwrite: true });

sourceFile.addClass(
    {
        name: "Test",
        extends: "Array<string>"
    });

sourceFile.formatText(
    {
        placeOpenBraceOnNewLineForControlBlocks: true,
        placeOpenBraceOnNewLineForFunctions: true
    });

console.log(sourceFile.getFullText());
```

***Output:***
```
class Test extends Array<string> {
}
```

**Expected behavior**

I expect the output to look like this:
```
class Test extends Array<string>
{
}
```

**Comment by dsherret** [comment]
I don't believe this is a bug. A class declaration is not a control block or function (control blocks are things like if statements). That said, I'm not sure why this only occurs when the class has extends or implements... (Edit: oh, I see in #1180)

Regardless, this is all compiler API code using their formatting API. If you want this feature I'd recommend asking for it in the typescript repo or fix it there. I'm going to close this because there's not anything actionable I can do.

Also, you may want to check out https://github.com/dprint/dprint and specifically https://github.com/dprint/dprint-plugin-typescript (which can be used in node via https://github.com/dprint/js-formatter and https://www.npmjs.com/package/@dprint/typescript). There is an option in there for placing the braces on a newline.
