### ISSUE TITLE
Decorator Arguments as String

### ISSUE THREAD

**Issue by ChazUK** [dsherret/ts-simple-ast#1205]
I'm trying to add a method with decorator to a class, the decorator also has a single argument of type string, but every time I try to add the argument it comes out without the wrapping quotation marks.

Version: 12.0.0

**To Reproduce**

```ts
import { Controller, Get } from '@nestjs/common';

@Controller('healthcheck')
export class HealthcheckController {}

```

```ts
import { Project } from "ts-morph";

const project = new Project();
const sourceFile = project.createSourceFile("test.ts", ``);

sourceFile.addImportDeclaration({
    namedImports: ['Get'],
    moduleSpecifier: '@nestjs/common',
});
const healthcheckController = sourceFile.getClass('HealthcheckController');
healthcheckController.insertMethod(0, {
    name: 'healthcheck',
    decorators: [
    {
        name: 'Get',
        arguments: ['hello'],
    },
    ],
});
const method = healthcheckController.getMethod('healthcheck');
method.setBodyText('return;');
sourceFile.organizeImports();
```

the final result is

```ts
import { Controller, Get } from '@nestjs/common';

@Controller('healthcheck')
export class HealthcheckController {
    @Get(hello)
    healthcheck() {
        return;
    }
}
```

Is there something I'm missing? Adding `typeArguments: ['string']` doesn't change the result

**Comment by dsherret** [comment]
@ChazUK put quotes around the text being inserted: `arguments: ["'hello'"],`

**Comment by ChazUK** [comment]
Thanks for the quick response, I'll go with ``arguments: [`'hello'`],``

Out of interest what does `typeArguments` do?

**Comment by ChazUK** [comment]
btw this had me stumped for a very long time because I was trying to end up with `@Get('/')` which of course was throwing an error as it was outputting `@Get(/)`

**Comment by dsherret** [comment]
`typeArguments` was supposed to write out the decorator's type arguments. I just committed a fix that will resolve this for the next release. Thanks for letting me know about that being broken.

Yeah, it's because someone may want the text not to have surrounding quotes (ex. inserting the identifier `hello` or number `1`) and ts-morph doesn't do any parsing of the text being inserted to discover if it should add quotes or not (because that would be hard to do, probably wrong a lot, and slow things down).
