### ISSUE TITLE
Smaller npm packages

### ISSUE THREAD

**Issue by gradzio** [dsherret/ts-simple-ast#1245]
**Is your feature request related to a problem? Please describe.**

I am developing vscode extension. I must add ts-morph as dependency to prod build. It is adding about 2mb which is quite big. 

I Am using mostly class / interface declaration with properties, constructor, methods and imports. 

Is there any way to use and build only these parts?
**Describe the solution you'd like**
It would be cool to have it split into eg @ts-morph/classes etc.

**Describe alternatives you've considered**
What can I do to shred the 2mb dependency?

**Comment by dsherret** [comment]
I wouldn't recommend using ts-morph in a vscode extension as it's not designed for this purpose though I know people have done this in the past. It will cause more memory to be used because it's not leveraging the language service that already exists in vscode. You may want to look into https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin instead.

The actual code in ts-morph is very intertwined and separating things would be too much of a maintenance burden unfortunately. I also don't think separating out just classes would save a lot of space. You may wish to manually trim out code from the ts-morph that you don't need and bundle it with your code.
