### ISSUE TITLE
Alignment of import statements

### ISSUE THREAD

**Issue by yackinn** [dsherret/ts-simple-ast#1260]
Awesome librabry. Thank you.

**Is your feature request related to a problem? Please describe.**

Is there a setting to align import by the "from" keyword?

**Describe the solution you'd like**
When using `createdFile.fixMissingImports()` or `createdFile.formatText()` we want the import statements to be 
aligned.

From this
```ts
import { EntityId } from "@omput/shared/util-backend";
import { IBookingResponse } from "../booking/booking.response.type";
import { CalculationType } from "./calculation-type.enum";
```

To this.
```ts
import { EntityId }         from '@omput/shared/util-backend';
import { IBookingResponse } from '../booking/booking.response.type';
import { CalculationType }  from './calculation-type.enum';
```

**Describe alternatives you've considered**

**Comment by lazarljubenovic** [comment]
Not an official statement since it's been a while since I used ts-morph, but I'm pretty sure you're better off if you format your code in a separate step using a separate tool (e.g. dprint by the same author or the "standard" solution like prettier, etc) instead of trying to do it all at once. It's probably possible, but I don't think ts-morph is too concerned with precision formatting like that.

**Comment by dsherret** [comment]
Yeah, this is out of scope for ts-morph. The `formatText` method just exposes the formatting api found in the TS compiler API so I don't make any adjustments to it.
