### ISSUE TITLE
getStructure can't get returnType

### ISSUE THREAD

**Issue by tyouzu1** [dsherret/ts-simple-ast#1293]
when write this, I can use `getStructure` to get `returnType` (`Promise<{ info: any; a: number }> `)
```ts
class xxx {
  async categoryInfo(): Promise<{ info: any; a: number }> {
    return {
       info: {},
       a: 123,
    }
  }
}
```

But  if I don't write `: Promise<{ info: any; a: number }>`, I can't get `returnType` anymore

I had to call `getReturnType` every method, to get returnType
```ts
method.getReturnType().getText() // `Promise<{ info: any; a: number }> `
```

<img width="495" alt="image" src="https://user-images.githubusercontent.com/26712711/173294313-50e00ca8-6937-42dc-9641-d70724bb1a29.png">

Version: 15.1.0

**Comment by dsherret** [comment]
`getStructure()` only returns what's in the AST. So that's why it shows when there is a return type node and it doesn't when there's not a return type node. If you want to find out the type regardless of whether there's a return type node or not, then you will need to use the type checker and call `method.getReturnType()` as you noted.

**Comment by tyouzu1** [comment]
thank you. got it
