### ISSUE TITLE
How can I get module export default node from AST?

### ISSUE THREAD

**Issue by lzs246** [dsherret/ts-simple-ast#1296]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/62453543/174775729-b2017fbf-716f-4f5d-ba89-8ea32ac4f438.png">

I want to get module export default Identifier through ts-morph?

I found that the node types for export dafault are all different.

How can I get the identifiers of all module export defaults?

For example, A in the picture above.

Thank

**Comment by jfangrad** [comment]
You'll notice that each of these (except for ExportAssignment) have a `DefaultKeyword` node as a child. You can search the Source file for a `DefaultKeyword` node and then call `getParent` on the result. There will also only be one `default` export in a file so that will make it easier.

The `ExportAssignment` case is special and is always a default export.

So something like the following should work for you:
```ts
const defaultKeywordNodes = sourceFile.getDescendantsOfKind(SyntaxKind.DefaultKeyword);
const exportAssignmentNode = sourceFile.getDescendantsOfKind(SyntaxKind.ExportAssingment);
// Only one of the two above results can be present since you can only have one default export
const parent = defaultKeywordNodes[0]?.getParent() ?? exportAssignmentNode;
```

This should at least be a good start. Might be an edge case I am missing but this should help. Might be an easier way that I am not aware of though without more exploration.

**Comment by lzs246** [comment]
Thank
