### ISSUE TITLE
ReadonlyArray-type is not properly recognized

### ISSUE THREAD

**Issue by Etienne-Buschong** [dsherret/ts-simple-ast#1305]
**Describe the bug**

Given a node of type `ReadonlyArray<...>`, the corresponding type is `any`.

Version: 15.1.0

**To Reproduce**

```ts
import { Project } from "ts-morph";

const project = new Project();
project.createSourceFile('test.ts', 'const x: ReadonlyArray<string> = [];');
const child: Node | undefined = project.getSourceFile('test.ts')?.getFirstChild();

console.log("Is array:", child?.getType().isArray()); // outputs "false"
console.log("Type text:", child?.getType().getText()); // outputs "any"
console.log("Type parameters: ", child?.getType().getTypeArguments()) // outputs "[]"
```

**Expected behavior**

The code above outputs `false` (for `isArray()`), `any` (for `getText()`) and `[]` (for `getTypeArguments()`).
The expected behaviour is that:
- `isArray()` outputs `true`. If not, how is an readonlyarray properly identified?
- `getText()` outputs `ReadonlyArray<string>`
- `getTypeArguments()` outputs an array of length 1

**Comment by dsherret** [comment]
Part of the reason this is occuring is because calling `getFirstChild()` on a source file will return its `SyntaxList`.

See and select Options (in top right corner) > Tree mode > getChildren():

https://ts-ast-viewer.com/#code/MYewdgzgLgBAHgLhgJQKYEMAm4A2BPAQQCcj08AeaIgSzAHMA+GAXhgG0BdAbiA

In this case, you want to get the variable declaration:

```ts
const project = new Project();
const sourceFile = project.createSourceFile('test.ts', 'const x: ReadonlyArray<string> = [];');
const varDecl = sourceFile.getVariableDeclarationOrThrow("x");

varDecl.getType().getText(); // "readonly string[]"
varDecl.getType().getTypeArguments().map(t => t.getText()); // [ "string" ]
varDecl.getType().getSymbolOrThrow().getName(); // "ReadonlyArray"
```

All this said, it does look like `.isArray()` returns `false` because the symbol doesn't have the name `Array`, but it should return it for this as well I think. Overall, it looks like the implementation of that method should be improved to be a bit more robust. I opened #1306 for that.

**Comment by Etienne-Buschong** [comment]
Regarding #1306: Would it make sense to add a distinct function `isReadonlyArray()` on types? Because `ReadonlyArray` is commonly used in many projects and it may makes sense to have a differentiation for them.
