### ISSUE TITLE
`getExpressionOrThrow` no longer exists on JsxElement in v16

### ISSUE THREAD

**Issue by oshi97** [dsherret/ts-simple-ast#1325]
**Describe the bug**

Version: 16.0.0

**To Reproduce**

`getExpressionOrThrow` no longer exists on JsxElement in v16. This doesn't appear to be present in the release notes for the 16.0.0 breaking changes

```ts
import { SyntaxKind, JsxAttribute } from 'ts-morph'

function doJsxThing(n: JsxAttribute) {
  const initializer = n.getInitializerOrThrow()
  if (initializer.isKind(SyntaxKind.StringLiteral)) {
    return
  }
  // no longer compiles
  const expression = initializer.getExpressionOrThrow()
}
```

**Expected behavior**

I think the code should compile if this isn't an expected change. Otherwise would appreciate an alternative!

**Comment by dsherret** [comment]
There are too many changes in TS 4.8 for me to document in the release notes as I don't have time, so I just say "upgraded to TS 4.8" as a breaking change.

Previously `JsxAttribute#getInitializerOrThrow()` returned `StringLiteral | JsxExpression`. In TS 4.8, they updated that to be `StringLiteral | JsxExpression | JsxElement | JsxSelfClosingElement | JsxFragment`:

https://github.com/dsherret/ts-morph/pull/1316/files#diff-1689901fc8d46451616bd34e0e34bf5c359401decc33ecd5fa7065f30525af6aR1403

So, the issue occurs because the jsx attribute initializer could be more things than possibly a `StringLiteral | JsxExpression` now. You will have to add extra checks for those other syntax kinds.

**Comment by oshi97** [comment]
Thank you!
