### ISSUE TITLE
Discussion: Is it possible to have ts-morph not move JSX elements to other lines until calling format text?

### ISSUE THREAD

**Issue by itsdouges** [dsherret/ts-simple-ast#1391]
Hello! I'm using ts-morph as the basis for a JSX editor for React Three Fiber. It works very well. Example video here: https://twitter.com/itsdouges/status/1628646325784023046?s=20

Currently it makes a few assumptions such as:

1. JSX element position is determined by line + column position
2. these positions won't change until saved (and thus formatting can move things to other lines)

Unfortunately (2) doesn't hold true. During a manipulation, primarily adding or updating JSX attributes, the position of JSX elements can change. Take this example:

```tsx
import Cylinder from "@/cylinder";
import Box from "src/box";
import { RoundedBox } from "@react-three/drei";
import Sphere from "./sphere";

export function SceneAlt() {
  return (
    <>
      <Box />
    </>
  );
}

export default function Scene() {
  return (
    <>
      <SceneAlt />
      <Box
        position={[-5.616274010653709, -1.4629692187526093, -4.804707725772893]}
        rotation={[
          2.1533738875424957, -0.4755261514452274, 0.22680789335122342,
        ]}
        scale={[1, 0.788966027180377, 1.977327619564505]}
      />
      <Cylinder
        position={[-2.7075824897598872, 0, 1.8652409214584758]}
      ></Cylinder>

      <Sphere
        scale={[0.630216523313958, 0.6302165233139577, 0.6302165233139577]}
        position={[
          4.333691919489441, 0.0017712872227060306, -4.677938097235295,
        ]}
      />

      <RoundedBox
        position={[3, 0, 2]}
        rotation={[0, 0.25, 0]}
        scale={[1, 1.5, 1]}
      >
        <meshStandardMaterial color="purple" />
      </RoundedBox>
    </>
  );
}
```

And then manipulating some JSX attributes:

```tsx
import Cylinder from "@/cylinder";
import Box from "src/box";
import { RoundedBox } from "@react-three/drei";
import Sphere from "./sphere";

export function SceneAlt() {
  return (
    <>
      <Box />
    </>
  );
}

export default function Scene() {
  return (
    <>
      <SceneAlt />
      <Box
        position={[-5.616274010653709, -1.4629692187526093, -4.804707725772893]}
        rotation={[
          2.1533738875424957, -0.4755261514452274, 0.22680789335122342,
        ]}
        scale={[1, 0.788966027180377, 1.977327619564505]}
      />
      <Cylinder
        position={[-2.7075824897598872, 0, 1.8652409214584758]}
      ></Cylinder>

      <Sphere
        scale={[0.630216523313958, 0.6302165233139577, 0.6302165233139577]}
        position={[0.8182080871598596,0.0017712872227060306,-1.6477179840071434]}
      />

      <RoundedBox
        position={[3, 0, 2]}
        rotation={[0, 0.25, 0]}
        scale={[1, 1.5, 1]}
      >
        <meshStandardMaterial color="purple" />
      </RoundedBox>
    </>
  );
}
```

In the second example the jsx element `Sphere`'s position prop changed, resulting in `RoundedBox` moving from L36 to L34, therefore things now aren't as expected.

Does anyone know if it's possible to enforce ts-morph to keep line numbers as much as possible during manipulations? At least for JSX elements being added/updated? So for example if a JSX element looks like this:

```
<Sphere
  scale={[0.630216523313958, 0.6302165233139577, 0.6302165233139577]}
  position={[0.8182080871598596,0.0017712872227060306,-1.6477179840071434]}
/>
```

If we were to update `scale` or `position` it would keep them on the same line. If we were to add a new prop, it would be on the same line (like so:)

```
<Sphere
  scale={[0.630216523313958, 0.6302165233139577, 0.6302165233139577]}
  position={[0.8182080871598596,0.0017712872227060306,-1.6477179840071434]} newProp={true}
/>
```

Keen for any insight. Also happy to contribute if this needs a code change.

**Comment by astahmer** [comment]
FWIW i've solved it by *not* using ts-morph for the manipulation
instead using [magic-string](https://github.com/rich-harris/magic-string) could help here, since it does just that :

> character indices always refer to the original string

 and it was also [way faster](https://github.com/astahmer/box-extractor/blob/main/packages/vanilla-wind/tests/str-manipulation.bench.ts)

**Comment by dsherret** [comment]
Yeah, using the add/insert/etc methods in ts-morph can be slow because it keeps track of the nodes while you work with them. Doing something that batches all the "text changes" together and executes them in one go will be faster https://ts-morph.com/manipulation/performance (there is also the `sourceFile.applyTextChanges` API not discussed there, but this will reparse the source file after so if you don't need to use the file after then you might want to apply it directly to the source file text... I should expose the function that makes it easier to do (currently called `getTextFromTextChanges` internally)).

> Does anyone know if it's possible to enforce ts-morph to keep line numbers as much as possible during manipulations?

It would unfortunately be too much work to maintain this.

Before and after a manipulation you can use `node.getLineNumber()` to see how the node position has changed, but this might start to get slow with lots of changes. Maybe using only text changes is the appropriate thing to do.

**Comment by dsherret** [comment]
One option I just thought about is to use the `node.replaceWithText(...)` api only. It will allow you to set the text for a node exactly like what you want.

https://ts-morph.com/manipulation/#replacing-any-node-with-new-text

**Comment by itsdouges** [comment]
Thanks both that's very insightful and I'll at least have a path forward 🙏.

And re: tsmorph keeping track of updated nodes, that's definitely the big feature that is a must have for me, I'm completely accepting it being slower 😊. I'll give your workaround a shot David and report back. If it works I could contribute a docs addition for this use case?

**Comment by itsdouges** [comment]
I'll close this one now, cheers all!
