### ISSUE TITLE
setIsExported does not work on VariableDeclaration

### ISSUE THREAD

**Issue by PuruVJ** [dsherret/ts-simple-ast#1401]
**Describe the bug**

Version: 18.0.0

`setIsExported` does not work on a node of type `VariableDeclaration`, but works on functions, interfaces, types

**To Reproduce**

https://stackblitz.com/edit/node-jjvpav?file=index.js,package.json

**Expected behavior**

Should work as expected

**Comment by dsherret** [comment]
You need to go up to the variable statement and export that. `VariableDeclaration` can't be exported, but `VariableStatement` can because variable statements can have multiple declaratoins.

```ts
varDecl.getVariableStatementOrThrow().setIsExported(true)
```

https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBAYwgOwM7wLYE8BqBDKOAXjgFYAaObAeRgAtgp9CSA2AbiA

See https://github.com/dsherret/ts-morph/issues/1267

**Comment by PuruVJ** [comment]
Thanks!
