### ISSUE TITLE
Does not understand destructure type params

### ISSUE THREAD

**Issue by ghost** [dsherret/ts-simple-ast#1537]
**Describe the bug**

Take this sample function
```ts
export default function({ a: string = null, b: number = null }) {
    
}
```

Now parse:
```ts
let declarations = file.getExportedDeclarations();
let fn = declarations["default"]
let parameters = fn.getParameters();
let type = parameters[0].getType().getText()
```

This prints:
```
"{ a?: any; b?: any; }"
```

Version: 22.0.0

**Expected behavior**

Should properly type this
```
{ a?: string; b?: number; }
```

**Comment by lazarljubenovic** [comment]
Those are not type params. You're just destructing the object and extracting the `a` property to a variable named `string` and `b` to a variable named `number`. Indeed the actual object is of type `{ a?: any, b?: any }` since there's no type annotation at all. They are optional because you give them default values.

**Comment by ghost** [comment]
whoops. You are a javascript superhero!
