### ISSUE TITLE
Performance for creating AST is “quadratically”-decreasing with size

### ISSUE THREAD

**Issue by derolf** [dsherret/ts-simple-ast#159]
I am using it for code generation from Protobuf-descriptions.

The more I add, the slower it gets. I see a lot of allocations.

**Comment by dsherret** [comment]
Yeah, there are some issues relating to performance that are open that should help a lot (#142, #141, and most likely #133 will help too). At the moment, functionality and correctness is the priority rather than performance, but it's definitely something I will be looking into in the future.

I made a substantial (but still not good enough) performance improvement in #70, so please ensure you are using a version >= 0.97.0.

My current recommendations are:

1. In the case you are storing a lot of code in one file, consider splitting up the code into many small files instead of using one large file.
2. Read this page: https://dsherret.github.io/ts-simple-ast/manipulation/performance

**Comment by derolf** [comment]
Thanks, Dave. I will try to “forget” :-)

**Comment by derolf** [comment]
I bumped to the latest version and am using “forget” now to forget parts of the AST I already created. Works like a charm!!!
