### ISSUE TITLE
Emitting declaration files not working as expected

### ISSUE THREAD

**Issue by atasak** [dsherret/ts-simple-ast#172]
When trying to emit code, the configuration is not working as expected. I tried different ways of configuring the tsc compiler, but with varying results. In some cases no code is emitted at all, and I havent been able to output the declaration files. 

test.ts: 
```
        const config = {
            ...
        };
        const ast = new Ast(config);
        ast.addSourceFiles('spec/common/**/*.ts');
        ast.emit();
```

tsconfig.json: 
```
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "declaration": true,
    "declarationDir": "spec/common/lib",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2015"
    ],
    "outDir": "spec/common/lib",
    "sourceMap": true
  },
  "include": [
    "spec/common"
  ]
}
```

- When using the tsconfig.json:
```
        const config = {
            tsConfigFilePath: 'tsconfig.json',
            compilerOptions: {
                declarations: true,
            }
        };
```
In this case, the javascript and code mappings are outputted correctly to spec/common/lib. The declaration files are missing though. 

- When using 
```
        const config = {
            tsConfigFilePath: 'tsconfig.json',
            compilerOptions: {
                out: 'spec/common/lib',
                declarations: true,
            }
        };
```
In this case, nothing gets outputted. 

- When omitting the declarations, nothing changes. 
- When omitting the tsconfig, nothing gets outputted. This is when including as wel as when omitting the `out: 'spec/common/lib'`. 

Tested on arch linux & windows 10 with: 
- tsc 2.6.2
- node 8.9.2
- ts-simple-ast 0.92.0

**Edit**
I failed to notice the upgrades from 1 to 3.2 in the last two weeks. The results seem to be the same, however.

**Comment by dsherret** [comment]
@atasak I will look into this, but two things I noticed:

1. Try using `declaration` instead of `declarations`.
2. It seems you want to use `outDir` instead of `out`. `out` is [deprecated](https://www.typescriptlang.org/docs/handbook/compiler-options.html) and is replaced by `outFile` now.

I will look into this more tonight though.

**Comment by dsherret** [comment]
I just noticed that in the first case, it should still be using `declaration: true` from the tsconfig.json. This seems like a bug to me.

**Comment by dsherret** [comment]
Hi @atasak, I haven't been able to reproduce the first example. In my case, the declaration files are outputted. Let me know if the above issues with using `declaration` instead of `declarations` and `outDir` instead of `out` fixes the issue, but if not, I'll do a release that implements and exposes enabling of a logger that logs what writes to the disk occur (I need to do this sometime soon anyway). Thanks!

**Comment by atasak** [comment]
Still not working... I have extracted a [minimum (not-)working example](https://github.com/dsherret/ts-simple-ast/files/1563195/emit_going_wrong.zip) from my project. Just run 

```
npm install
npm run build
npm run run
```

the tests.ts file is located in `spec/common` and the output dir is set to `spec/common/lib`. In src/compiler/compiler/testschemer.ts, the line including the tsconfig is currently commented out. I cannot figure out what's going wrong...

**Comment by dsherret** [comment]
Thanks, I will take a look this weekend!

**Comment by dsherret** [comment]
Hey @atasak, I looked into this. I should have thought about it earlier. Basically what's happening here is that there is a compile error in the code when using `declaration: true`. In this case, the compile error is:

> 'Parameter 'b' of public method from exported class has or is using private name 'B'.

The problem can be fixed by exporting `B` from the file.

You can view these compile errors by calling either:

```ts
const compileErrors = ast.getDiagnostics();
// or
const emitResult = ast.emit();
console.log(emitResult.getDiagnostics());
```

I've updated the documentation on emitting to make this more clear. Sorry about this confusion!

**Comment by atasak** [comment]
Ah, thanks. This will help a lot. As for using the `outDir` instead of `out`, you might want to update [the emitting documentation page](https://dsherret.github.io/ts-simple-ast/emitting). In the first line of code (`const ast = new TsSimpleAst({ compilerOptions: { out: "dist", declaration: true } });`), the `out` is still used. 

Thanks for your help!

**Comment by dsherret** [comment]
Thanks, I just updated the docs! :)

I see why they deprecated that compiler option now—too ambiguous.
