### ISSUE TITLE
TypeGuard for all nodes with a .expression?

### ISSUE THREAD

**Issue by gregjacobs** [dsherret/ts-simple-ast#187]
Hey David,

Was just working on some AST transforms, and I noticed a pattern that I want to try to take advantage of.

I'm basically trying to replace identifiers such as `myVar` with `this.myVar`. I noticed that I basically need to find compiler nodes which have an `expression` property that contain an `Identifier` node. 

For example, `CallExpression`, `PropertyAccessExpression`, `IfStatement`, and probably many more have an `expression` property. Was thinking I could transform them with something like this: 

```ts
// ...traversing nodes
if( TypeGuards.isExpressionableNode( node ) ) {  // <-- does this name make sense?
    if( TypeGuards.isIdentifier( node.getExpression() ) { 
        node.getExpression().replaceWithText( 'this.' + node.getExpression().getText() );
    }
}
```

Btw, any general thoughts on this? Is there a better way to go about this?

**Comment by dsherret** [comment]
You're right, this is very common. I'll make all the nodes that have this an `ExpressionableNode`. Then yes, you will be able to just do `TypeGuards.isExpressionableNode(node)`

**Comment by dsherret** [comment]
@gregjacobs I added `TypeGuards.hasExpression`. This will return true when the node has a `.getExpression()` method and that method returns true.

The second check is necessary because `.getExpression()` could possibly return undefined for certain statements like `ReturnStatement` (`return 5;` vs `return`) and `YieldStatement` (`yield 5;` vs `yield;`).

I'm running a new release now.

**Comment by gregjacobs** [comment]
Awesome, thanks man!
