### ISSUE TITLE
Add the ability to rename / move SourceFiles

### ISSUE THREAD

**Issue by gregjacobs** [dsherret/ts-simple-ast#199]
Would be nice to be able to rename or move a `SourceFile` to a different directory.

**Comment by dsherret** [comment]
Yeah, this is something I would like... current code is to do the following:

```ts
const newFile = file.copy("newFile.ts");
await Promise.all([newFile.save(), file.delete()]);
```

**Comment by gregjacobs** [comment]
Hehe, no worries. I'm actually doing my 'rename' after all of my transformations at this point, but good to know! Thanks for the workaround in the meantime - didn't even see that there was a `delete()` method on SourceFile :)

**Comment by dsherret** [comment]
This will be implemented in version 8 (releasing in a few minutes). I had to do some major changes to how this library works behind the scenes to implement this. Now all changes won't be propagated to the file system until calling `.save()` on the main ast object:

```ts
import Ast from "ts-simple-ast";

const ast = new Ast();

// ...lots of code here that manipulates, copies, moves, and deletes files...

// when you're all done, call this and it will save everything to the file system
ast.save();
```

This is so that if the code manipulation fails halfway through, the file system won't be left in a halfway state. If you want to move or copy files immediately to the file system, then use the `moveImmediately()` and `copyImmediately()` methods.

**Comment by dsherret** [comment]
By the way, IMO this feature is pretty cool. It will handle changing any import and export declarations' module specifiers in the moving file and the files referencing that file. Unfortunately, it's kind of slow because of that... in the future I want to look into ways of speeding that up.

**Comment by gregjacobs** [comment]
Hey man, sorry for the delayed response. This sounds awesome, and nice job on that with fixing up all of the import and exports too! 

I actually just ran into a situation a couple of days ago where this renaming will be super useful and simplify my code big time. Will let you know how it goes - thanks for this!

**Comment by gregjacobs** [comment]
Btw, sounds good on having a quick lookup structure for figuring out how files relate in order to facilitate quicker renames. +1 on that :)

**Comment by dsherret** [comment]
No problem, I hope it works out!

Just another note... it currently doesn't work for `require` statements atm. I'll do that once the graph is implemented because otherwise moving would be way too slow. I feel that there must be some way to get how files relate from the compiler API though... I'd like to figure that out before implementing my own way of doing it.

**Comment by gregjacobs** [comment]
Yeah that's a good question if it's possible to get from the compiler API or not. I do know there are some other npm modules out there though that will build and return an adjacency list dependency graph of all of the imports. Maybe you could leverage something like that?

**Comment by dsherret** [comment]
I looked around a bit, but didn't immediately find anything using the TypeScript compiler. I also briefly just looked at the code for `findReferences` in the TypeScript repo, but I didn't find anything useful in there yet (maybe `getImportersForExport`). I'll have to look back again later.

**Comment by dsherret** [comment]
FYI, it uses a lazy graph now in v9.4.0 so it should be way faster for moving lots of files.

I talked with the Typescript team and they told me about `getAllDependencies` in `BuilderProgram`, but it seems dependent on compilation (ex. returning all files when specifying the outFile or out compiler options). So I had to roll with my own implementation.
