### ISSUE TITLE
Add missing Expression classes

### ISSUE THREAD

**Issue by dicarlo2** [dsherret/ts-simple-ast#213]

**Comment by dsherret** [comment]
If you work on this, would you mind moving the `expressions` to their own folder? Right now they're in `compiler/common`, but it would be better if they were moved to `compiler/expression`.

**Comment by dsherret** [comment]
@dicarlo2 can we can close this issue now? Thanks once again for all your help! You did a great job here... I barely had to give any feedback.

**Comment by dicarlo2** [comment]
Yea, I'm pretty sure this is complete, if I missed any I'll open another issue.

**Comment by dicarlo2** [comment]
Thanks again for the speedy reviews!

**Comment by dsherret** [comment]
Cool, this is released in v5.5.

By the way, fun fact: Node.d.ts is over 15,000 lines long since there's so many new wrapped nodes... the release took 10 minutes to run in order to generate all the overloads (ex. `getFirstChildIfKind(kind: ts.SyntaxKind.Block): compiler.Block | undefined;`). I think I'm going to make the js docs a single line. Also, in the future I'm going to need to work on improving the performance so that it's a bit quicker when working on large files.
