### ISSUE TITLE
[BUG] getNameNode is not a function for propertyAccessExpression

### ISSUE THREAD

**Issue by vogloblinsky** [dsherret/ts-simple-ast#253]
Moving from 6.12.0 to 7.x

For this code which replace code, i have an error `TypeError: propertyAccessExpression.getNameNode is not a function`

```
const propertyAccessExpressions = file.getDescendantsOfKind(ts.SyntaxKind.PropertyAccessExpression)
    .filter(p => !TypeGuards.isPropertyAccessExpression(p.getParentOrThrow()));

// inline the property access expressions
for (const propertyAccessExpression of propertyAccessExpressions) {
    const referencedDeclaration = propertyAccessExpression.getNameNode().getSymbolOrThrow().getValueDeclarationOrThrow();
    if (!TypeGuards.isPropertyAssignment(referencedDeclaration))
        throw new Error(`Not implemented referenced declaration kind: ${referencedDeclaration.getKindName()}`);
    propertyAccessExpression.replaceWithText(referencedDeclaration.getInitializerOrThrow().getText());
}
```

**Comment by dsherret** [comment]
Upgrade to v7.1 (it includes everything from the compiler now on the `ts` named export) and make sure you are using `SyntaxKind` from the library:

```ts
import {SyntaxKind} from "ts-simple-ast";
```

The reason it doesn't work above is because the `SyntaxKind` values in TypeScript v2.7.1 are probably different from the TypeScript compiler version of the `ts` object.

The peer dependency on TypeScript was dropped in v7.0 so that new language features can be supported and so that this library is not stuck with one.

**Comment by dsherret** [comment]
As discussed on Twitter, the issue was with the SyntaxKinds (as alluded to above).

For anyone else reading this:

If you'd like to use ts-simple-ast mixed with the compiler, what you might want to consider doing is replacing all `import * as ts from "typescript";` calls with `import {ts, SyntaxKind} from "ts-simple-ast";`, then replace all `ts.SyntaxKind` references with just `SyntaxKind`, and finally drop the dependency on TypeScript from package.json. If this would be a big refactor, then I recommend writing a script using this library that will do the refactoring for you.

**Comment by vogloblinsky** [comment]
Thanks. All the code of compodoc has been fixed to only use ts-simple-ast TypeScript wrapper. Works fine.
