### ISSUE TITLE
Cannot find name Constructor

### ISSUE THREAD

**Issue by sfrooster** [dsherret/ts-simple-ast#32]
I'm getting about 90 of these errors, all originating from this library in node_modules.  I don't know why they're being generated (tsc shouldn't be tying to compile anything in node_modules) but I do note that I can't seem to find a "Constructor" defined anywhere in the library - so I don't know what's going on.

**Comment by dsherret** [comment]
Thanks for the heads up! I've been working on this library within itself and haven't tried importing it from the outside for a while. I'll have to setup an automated test to make sure this doesn't happen again (Opened #33).

I was able to reproduce the error you mentioned and this should be fixed in 0.28.1. Let me know if this fixes the problem for you or if you have any other issues.

**Comment by sfrooster** [comment]
Yes, this does appear to be fixed in 0.28.1!  I'm having new issues now which may be by design.  I'll open a separate issue for each of those.
