### ISSUE TITLE
How to pass an ObjectLiteralExpression as an initializer to addVariableStatement?

### ISSUE THREAD

**Issue by derolf** [dsherret/ts-simple-ast#320]
Right now, VariableDeclarationStructure exposes initializer just as a string, but I want to construct something like:

```
foo: {
  bar: 1,
  zoo: "test"
}
```

**Comment by dsherret** [comment]
Hey @derolf, yeah I've thought about that, but not sure what the best way would be at the moment. I still have to think about it a bit more. This is somewhat related to #148, but not exactly.

What I will do in the short term is improve `VariableDeclarationStructure` to accept a writer function and that would make doing this a little easier, but still not ideal. I'll get that done soon and comment back here when it's done.

**Comment by dsherret** [comment]
In v11 it's possible to use a writer when creating a variable declaration:

```ts
sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [{
        name: "myVar",
        initializer: writer => {
            writer.inlineBlock(() => {
                writer.writeLine("bar: 1,")
                    .writeLine(`zoo: "test"`);
            });
        }
    }]
});
```

I haven't tested that, but it should be a little easier to use than before. You could even extract that out to a reusable function and then write something like: `initializer: writer => objToString(writer, { bar: 1, zoo: "test" })` and in that function call the code that formats things like above.

Anyway, I'm going to keep looking into this and evaluate how I can make this easier because it definitely is a pain point. I just have to figure out how it would work.

**Comment by derolf** [comment]
Hm, that’s kind of hack. Better would be to be able to pass a structured Initializer-Expression.

**Comment by dsherret** [comment]
Added `WriterHelpers` class for doing this:

```ts
import { WriterHelpers } from "ts-simple-ast";

// ...etc...

sourceFile.addVariableDeclaration({
    name: "myVarDeclaration",
    initializer: writer => WriterHelpers.writeObject(writer, {
        key1: 5,
        key2: "undefined",
        key3: writer => writer.quote("someString"),
        key4: undefined
    })
});
```

Outputs:

```ts
let myVarDeclaration = {
    key1: 5,
    key2: undefined,
    key3: "someString",
    key4
};
```

I'm not going to go with specific methods for doing this because it should be sufficient to use the writer function.
