### ISSUE TITLE
[BUG] Barrel file support

### ISSUE THREAD

**Issue by vogloblinsky** [dsherret/ts-simple-ast#327]
Starting with this issue : https://github.com/compodoc/compodoc/issues/566

With this files structure :

```
.
├── metadatas
│   ├── footer
│   │   └── footer-component.metadatas.ts
│   └── index.ts
└── footer.component.ts
```

This file breaks in 
```
// footer.component.ts
import { FooterComponentSchema } from './metadatas';

/**
 * The footer component
 */
@LogClass
@Component(FooterComponentSchema)
export class FooterComponent {
```

with this error :

```
Error: File not found: /Volumes/Data/wamp/Projets/open-source/compodoc/compodoc-demo-todomvc-angular2/src/app/footer/metadatas.ts
    at FileNotFoundError.BaseError [as constructor] (/Volumes/Data/wamp/Projets/open-source/compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new FileNotFoundError (/Volumes/Data/wamp/Projets/open-source/compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/FileNotFoundError.js:8:28)
    at Project.addExistingSourceFile (/Volumes/Data/wamp/Projets/open-source/compodoc/compodoc/node_modules/ts-simple-ast/dist/Project.js:188:19)
```

This works :
```
// footer.component.ts
import { FooterComponentSchema } from './metadatas/index';

/**
 * The footer component
 */
@LogClass
@Component(FooterComponentSchema)
export class FooterComponent {
```

**Comment by dsherret** [comment]
Hey Vincent, how have you been? I took a look at [imports.util.ts](https://github.com/compodoc/compodoc/blob/11a742c13876794c45cd8e5bc8aaba62307bbb6e/src/utils/imports.util.ts#L110) and the problem seems to be in there.

```ts
let importPath = path.resolve(
    path.dirname(sourceFile.fileName) +
        '/' +
        searchedImport.getModuleSpecifierValue() + // <-- right here
        '.ts'
);
const sourceFileImport =
    typeof ast.getSourceFile(importPath) !== 'undefined'
        ? ast.getSourceFile(importPath)
        : ast.addExistingSourceFile(importPath); // tslint:disable-line
```

After finding out that `importPath` doesn't exists, you'll want to check if `importPath` with `.ts` is a directory containing an `index.ts` file. Also, you'll want to use `addExistingSourceFileIfExists` instead of `addExistingSourceFile`.

That said, there is a convenient `importDeclaration.getModuleSpecifierSourceFile()` that you may want to use here... it uses the symbols so it will be a little slower, but should hopefully be accurate. Note that if the module resolution of the compiler is `Classic` then it won't resolve those implicit *index.ts* module specifiers. So for example, if the `moduleResolution` compiler option isn't explicitly set then setting the `module` compiler option to anything but `ModuleKind.CommonJS` will cause the module resolution kind to resolve to `Classic`. Additionally, if `moduleResolution` and the `module` compiler option isn't set, then a script target of `ES2015` and above will also use `Classic` module resolution. Hopefully I've explained that correctly and I have no idea why it's this way in the compiler...

---

Sidenote: I really dislike my design for `Project` not being able to have this line in a single method call. `const sourceFileImport = typeof ast.getSourceFile(importPath) !== 'undefined' ? ast.getSourceFile(importPath) : ast.addExistingSourceFile(importPath);` -- I've done this too in some other libraries that use ts-simpel-ast.

Would a `const sourceFileImport = ast.getOrAddExistingSourceFile(importPath);` method be nice? Or can you think of a better name? I guess that one makes sense.

**Comment by dsherret** [comment]
Hi @vogloblinsky, very sorry... forgot to respond. I forget exactly what you're trying to do here, but calling `findReferences()` is a good way to use the language service to have a behaviour similar to "Find references" in an IDE. There's also `findReferencesAsNodes()` which will return the nodes that reference the definition (just released in latest minor... it will eventually deprecate `.getReferencingNodes()`).

**Comment by vogloblinsky** [comment]
Thanks David, i will look that asap.
