### ISSUE TITLE
Create object literal AST from JSON

### ISSUE THREAD

**Issue by derolf** [dsherret/ts-simple-ast#350]
It would be nice to create a partial AST from a object literal tree.

This way, we could parse a JSON and directly emit a partial AST that represents the parsed JSON.

**Comment by cancerberoSgx** [comment]
Currently I'm working on providing node to structure support  (https://github.com/dsherret/ts-simple-ast/pull/346) . When that's finish and since 1) structures are data objects easily converted to JSON and 2) Nodes already support fill() from structure I think implementing this should be trivial. My two cents.

**Comment by cancerberoSgx** [comment]
If you are in a hurry, I think you can accomplish it anyway with something like this : https://github.com/blakeembrey/javascript-stringify

If you security is a risk there are safe alternatives to eval() . my two cents.

**Comment by derolf** [comment]
Yeah, that javascript-stringify looks nice, I can bake it into a string and fill an assignment with that stuff. Thanks!

**Comment by cancerberoSgx** [comment]
if you try it tell us if it works or problems you had - I think it should handle circular dependencies OK but I never used - thanks!

**Comment by dsherret** [comment]
I believe #346 will cover this. Please reopen this issue if that's not the case.
