### ISSUE TITLE
Issue with constructor defined members/properties

### ISSUE THREAD

**Issue by sfrooster** [dsherret/ts-simple-ast#39]
To be clear, it's an overloaded constructor:

```typescript
        constructor();
        constructor(Email: string, FirstName: string, LastName: string, SecurityToken: string);
        constructor(public Email: string = "", public FirstName?: string, public LastName?: string, public SecurityToken?: string) {
            super();
        }
```

Neither getInstanceMembers nor getInstanceProperties returns any of those.

**Comment by dsherret** [comment]
I could have sworn I thought about function overloads. In this case, it's definitely better for us to stick exactly with the AST so I'll change `getConstructor()` to `getConstructors()`.

**Comment by sfrooster** [comment]
But isn't the issue that those parameters should be available in... I'm guessing getInstanceMembers?

**Comment by dsherret** [comment]
Oh yeah, completely glossed over that because I started thinking about overloads. Anyway, the overload issue is fixed in 0.36.0. I think it's fair that the parameters would be returned in getInstanceProperties() and getInstanceMembers().

**Comment by sfrooster** [comment]
Great - I really appreciate your responsiveness!

**Comment by dsherret** [comment]
Ok, implemented in 0.37.0. I also fixed up some of the return types for these methods on ClassDeclaration... they were sometimes including types that would never be returned (too bad that typescript can't implicitly figure this out atm via the filter method).

Closing this. Let me know if this is still an issue. Also, I just happened to be around right now and I'm only doing quick fast releases because this is still very much a work in progress and experimental :)

**Comment by sfrooster** [comment]
I'll give it a shot this evening!

**Comment by sfrooster** [comment]
It does look like I'm getting these values now.  One distinction - and maybe I'm wrong here - but properties are constructs like:
```typescript
    private _testField: string = null;
    get fieldName() : string {
        return this._testField;
    }
    set fieldName(name : string) {
        this._testField = name;
    }
```
This piece seemed to be working correctly before.

I don't think there's a way to define a property via the constructor parameters in which case those should only be appearing in the getAll/InstanceMembers return values whereas they are also being returned in the from the getInstanceProperties method call.

In any case, if I'm wrong, happy to be corrected but the "public" constructor params are now showing up as members.

**Comment by sfrooster** [comment]
The following error seems to have been introduced (I don't think it's my config):

node_modules/ts-simple-ast/dist/compiler/common/Node.d.ts(6,22): error TS2420: Class 'Node<NodeType>' incorrectly implements interface 'IDisposable'.
  Property 'dispose' is missing in type 'Node<NodeType>'.

**Comment by dsherret** [comment]
Sorry, Disposable error is gone in 0.37.1. I was trying to hide the dispose method because it's internal to the library, but forgot to hide it in the interface too. I still haven't implemented #33.

So parameters with a scope in a constructor are officially called "parameter properties" (see here)[https://www.typescriptlang.org/docs/handbook/classes.html]. I think it's better to include them in `getInstanceProperties()` because it will cause people who use this library to not forget about them (like how I forgot about them in this issue :)). It will give them a reminder that constructor parameters can possibly be properties too and that might be something they need to handle. If they don't need to worry about them, they can filter the parameters out of the returned results.

**Comment by dsherret** [comment]
I just re-read over that doc. I need getInstanceProperties() to also return a result when people use the `readonly` keyword hah. I'll fix that in 0.37.2

**Comment by sfrooster** [comment]
Ok, I've just pulled this and will clean-up my code accordingly.  Also, thanks for the clarification on parameter properties - very helpful!

**Comment by dsherret** [comment]
@sfrooster fyi, in the upcoming 0.43.0, most methods in this library will only return the implementations of functions, methods, and constructors except when it's ambient. You can get the overloads by calling `.getOverloads()` on the functions.

So for example:

```typescript
const code = "function myFunction(str: string); function myFunction(num: number); function myFunction(strOrNum: string | number) {}";
const ast = new Ast();
const sourceFile = ast.addSourceFile("file.ts", code);

// this returns only 1 function declaration (the implementation) instead of 3
sourceFile.getFunctions();

const myFunction = sourceFile.getFunction("myFunction")!;
myFunction.getOverloads(); // returns the 2 overloads
```

That said...

```typescript
const code = "declare function myFunction(str: string); declare function myFunction(num: number);`";
const ast = new Ast();
const sourceFile = ast.addSourceFile("file.ts", code);

// this returns the two function declarations because there is no implementation
sourceFile.getFunctions();
```

^ I'm mentioning this here because the same applies to `getConstructors()`
