### ISSUE TITLE
Getting class properties could use improvement

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#58]
Right now getting properties is somewhat annoying. I want to avoid people having to use assertions. I think it would be nice to add an additional parameter that specifies the kind of property.

Need to think about this more...

**Idea 1**

```typescript
enum PropertyKind {
    Property,
    GetAccessor,
    SetAccessor,
    Parameter
}

// prop would be typed as PropertyDeclaration and only return properties that match that kind
const prop = classDeclaration.getInstanceProperty("name", PropertyKind.Property);
```

Pros: Less methods. User could still use type guards if they don't like this.
Con: Need to import an additional enum (annoying for something that's so common to do)

**Idea 2**

Have these methods:

```typescript
classDeclaration.getAllProperties();
classDeclaration.getProperties();
classDeclaration.getProperty(...);
classDeclaration.getSetAccessors();
classDeclaration.getSetAccessor(...);
classDeclaration.getGetAccessors();
classDeclaration.getGetAccessor(...);
classDeclaration.getParameterProperties();
classDeclaration.getParameterProperty(...);
classDeclaration.getAllStaticProperties();
classDeclaration.getStaticProperties();
classDeclaration.getStaticProperty(...)
classDeclaration.getStaticSetAccessors();
classDeclaration.getStaticSetAccessor(...)
classDeclaration.getStaticGetAccessor(...);
```

Pro: Easy to quickly use.
Cons: Too many methods. Might not be obvious that getProperties() doesn't return set and get accessors.

**Comment by atasak** [comment]
My thoughts on this: 

I would personally prefer option 2. I don't think comparing enum constants is any better than instanceof. I think it's actually worse, because in typescript an `if-instanceof` will do an implicit cast, whereas when comparing enum constants you'll have to cast manually. The second option removes these issues altogether, as you could return everything with the correct type. This will in most cases result in much cleaner code. 

It might indeed not be clear what `getProperties` would do, but why not renaming it to `getVarProperties`? 

As for the first option having less methods: I think that would be a non-argument, as you already split for example `getMethods` and `getProperties`.

**Comment by dsherret** [comment]
@atasak yes, I'll be doing something like option 2 here. The current behaviour will remain largely the same... just there will be way more methods.

**Comment by dsherret** [comment]
The necessary changes related to this were made in #266.
