### ISSUE TITLE
QU: How do replace the value of JS object key with a string (or more generally, how do I create JS object structures?)

### ISSUE THREAD

**Issue by chrisgervang** [dsherret/ts-simple-ast#64]
Thanks again for your help with my last question! Super helpful and thoughtful response! :) 🥇 

I've got three more bodies of text I'm trying to generate (seen below as three commented out sections). I was wondering if you had any ideas on how to replace/insert into a object or array. Or, if simpler, is there a way to replace the variable's value with a string I provide?
```
const init = {
    component: // "ImportedComponentName",
    props: [
        // {   
        //     type: "string",
        //     label: "src",
        //     defaultValue: ""
        // }
    ]
}

class Story extends React.Component<any, {}> {
    static defaultProps = {
        // src: getDefault(init, "src"), 
        // scale: getDefault(init, "scale")
    }
}
```

I tried figuring out how to use the function you added today called `TsSimpleAst.setBodyTextForNode`, but I'm not familiar enough with the compiler to know why I was having trouble. 

I attempted to replace `init.component` with this code, but `compilerNode` isn't defined and I ran out of ideas:
```
const init = story.getVariableDeclaration("init")
const p = init.compilerNode.initializer.properties
// const body = p[0].compilerNode.body // -> undefined
const node = init.global.compilerFactory.getNodeFromCompilerNode(p[0], init.sourceFile)
TsSimpleAst.setBodyTextForNode(node, "new value!")
// Error:
// const childSyntaxList = body.getChildSyntaxListOrThrow();
//                                 ^
// TypeError: body.getChildSyntaxListOrThrow is not a function
//    at Object.setBodyTextForNode (/Users/chrisgervang/code/pi
```

**Comment by dsherret** [comment]
That's strange... I have `setBodyTextForNode` marked as internal so it shouldn't be showing up. I've made that function unavailable in 0.56.1 because it shouldn't be public. It only works with nodes that have a `setBodyText(text: string);` method—it's used by the `setBodyText` method in `BodyableNode` and `BodiedNode`.

In this scenario, on `VariableDeclaration` and `PropertyDeclaration` there is a method called `setInitializer()` that you can use:

```typescript
init.setInitializer(`"some string"`); // const init = "some string";
init.setInitailizer("{ obj: 5 }"); // const init = { obj: 5 };
```

----

Unfortunately, right now there is no way to manipulate JS object structures. It's something I'd like to add though.

**Comment by dsherret** [comment]
Closing this in favour of #65. Please feel free to reopen if this doesn't solve your issue.
